[package]
name = "mol_diffusion"
version = "0.1.0"
authors = ["tungli <tun@mail.muni.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ode_solvers = "0.3.0"
nalgebra = "0.17"
typenum = "1.11"
